"""empty message

Revision ID: 28672c3ae431
Revises: 7a84fc1ec81e
Create Date: 2021-04-04 22:55:11.845853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28672c3ae431'
down_revision = '7a84fc1ec81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('isDone', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'isDone')
    # ### end Alembic commands ###
