"""empty message

Revision ID: f0f97f801787
Revises: 28672c3ae431
Create Date: 2021-04-04 23:35:34.267280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f97f801787'
down_revision = '28672c3ae431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('ddl', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'ddl')
    # ### end Alembic commands ###
